[build-system]
requires = ["setuptools>=69.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "letterboxd-api"
version = "1.0.0"
dynamic = ["dependencies"]
requires-python = "==3.11"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }