name: Scrape

on:
    schedule:
        - cron: "0 8 * * *" # runs every day at 8:00 AM UTC (2:00 AM CST / 3:00 AM CDT)
    workflow_dispatch: # enables manual triggering

jobs:
    run_scraper:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Set up environment variables
              run: |
                  echo "DB_URI=${{ secrets.DB_URI }}" >> .env
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                  echo "DB_USERS_COLLECTION=${{ secrets.DB_USERS_COLLECTION }}" >> .env
                  echo "DB_FILMS_COLLECTION=${{ secrets.DB_FILMS_COLLECTION }}" >> .env
                  echo "DB_MODELS_COLLECTION=${{ secrets.DB_MODELS_COLLECTION }}" >> .env
                  echo "DB_SUPERLATIVES_COLLECTION=${{ secrets.DB_SUPERLATIVES_COLLECTION }}" >> .env
                  echo "LETTERBOXD_USERNAMES=${{ secrets.LETTERBOXD_USERNAMES }}" >> .env
                  echo "LETTERBOXD_GENRES=${{ secrets.LETTERBOXD_GENRES }}" >> .env
                  echo "ENV=${{ secrets.ENV }}" >> .env

            - name: Run scraper
              run: python -m scrape.scraper
            - name: Compute stats
              run: python -m scrape.stats
            - name: Train prediction model
              run: python -m prediction.train_model
